DataBiosphere/cbas

- .github/workflows/publish.yml
- .github/workflows/tag.yml
- service/publishing.gradle
- service/src/main/java/bio/terra/cbas/app/App.java
- Adds docker build via jib
- Adds a tag action which updates the project and creates a github tag
- Adds docker publish to dockerhub via github action, triggered whenever a github tag is created
> CBAS Docker build and publish [BW-1178]

- .github/workflows/publish.yml
- .gitignore
Sample image that was published by this action, triggered manually: https://console.cloud.google.com/gcr/images/broad-dsp-gcr-public/global/composite-batch-analysis-service?project=broad-dsp-gcr-public
> BW-1178 Add publish to GCR

- .github/workflows/build-and-test.yml
- buildSrc/src/main/groovy/java-common-conventions.gradle
- service/build.gradle
- service/src/test/java/bio/terra/cbas/app/HelloWorldTest.java
Confirmation that the output appears in the [Details](https://github.com/DataBiosphere/terra-batch-analysis/runs/6580537065?check_suite_focus=true) log:
```
> Task :service:test
HelloWorldTest > addition() PASSED
---------------------------------------------------------------
|  Results: SUCCESS (1 tests, 1 passed, 0 failed, 0 skipped)  |
---------------------------------------------------------------
```
Note to self:
> BW-1183: Run unit tests on PRs

- service/src/main/java/bio/terra/cbas/controllers/PublicApiController.java
@pshapiro4broad I think this should do the trick; though I'm admittedly not sure the nested `try` is a nice pattern.
If not I will just adopt your suggestion literally and forget about the timeout stuff for now, so I can move on to something more important.
Thank you for your reviews, they are super helpful!
> BW-1288 Auto close stream

- service/src/main/java/bio/terra/cbas/controllers/RunsApiController.java
Closes https://broadworkbench.atlassian.net/browse/BW-1284
> BW-1284 Pass workflow inputs to Cromwell

- .github/workflows/publish.yml
Closes https://broadworkbench.atlassian.net/browse/BW-1296
> BW-1296 Publish CBAS image to new cbas repo in DockerHub and GCR

- common/openapi.yml
- service/build.gradle
- service/src/main/java/bio/terra/cbas/controllers/RunsApiController.java
Closes https://broadworkbench.atlassian.net/browse/BW-1305
> BW-1305 Adds GET /runs endpoint

- .github/workflows/publish.yml
- settings.gradle
Successful workflow run: [#60](https://github.com/DataBiosphere/cbas/runs/7796722849?check_suite_focus=true)
Cromwhelm commit where CBAS version was updated: [afcc0ec](https://github.com/broadinstitute/cromwhelm/commit/afcc0ecaf3dddf90ab00c164598055cc85c6d5aa)
Closes https://broadworkbench.atlassian.net/browse/BW-1384
> BW-1384 Publish workflow successfully updates CBAS version in cromwhelm helm charts 

- service/src/main/java/bio/terra/cbas/config/WdsServerConfiguration.java
- service/src/main/java/bio/terra/cbas/controllers/PublicApiController.java
- service/src/main/resources/application.yml
Example response when WDS is being hosted on localhost:8001:
And when WDS is not running:
> BW-1368: Add WDS config and healthcheck

- common/openapi.yml
- service/src/main/java/bio/terra/cbas/controllers/RunsApiController.java
> BW-1390 Porting postRun endpoint

- .github/workflows/publish.yml
Closes https://broadworkbench.atlassian.net/browse/BW-1427
> [BW-1427] Update Github workflow action publish.yml to update image version in cromwhelm

- service/build.gradle
- service/src/main/java/bio/terra/cbas/app/App.java
- service/src/main/java/bio/terra/cbas/common/MetricsUtil.java
- service/src/main/java/bio/terra/cbas/runsets/monitoring/SmartRunsPoller.java
To see these metrics locally:
- Run CBAS and open http://localhost:9098/
- Install prometheus (eg `brew install prometheus`)
- Create a sample prometheus config, like below
```
scrape_configs:
- job_name: 'ocjavametricstutorial'
scrape_interval: 10s
static_configs:
- targets: ['localhost:9098']
```
- Run prometheus with: `prometheus --config.file=promconfig.yaml`
> BW-1404: First metrics code

- service/build.gradle
Removes a bunch of superfluous and confusing API options
> WM-1429: Bump WDS version

- service/build.gradle
- service/src/test/java/bio/terra/cbas/runsets/inputs/TestInputGeneratorBuildInputs.java
Relates to changes made in https://github.com/DataBiosphere/terra-workspace-data-service/pull/118/
> AJ-617: Remove RecordMetadata from WDS and all downstream references, including CBAS

- common/openapi.yml
- service/src/main/java/bio/terra/cbas/common/DateUtils.java
- service/src/main/java/bio/terra/cbas/controllers/RunSetsApiController.java
- service/src/main/java/bio/terra/cbas/controllers/RunsApiController.java
- service/src/main/java/bio/terra/cbas/dao/RunDao.java
- service/src/main/java/bio/terra/cbas/dao/RunSetDao.java
- service/src/main/java/bio/terra/cbas/dao/RunSetMapper.java
- service/src/main/java/bio/terra/cbas/models/CbasRunSetStatus.java
- service/src/main/java/bio/terra/cbas/models/Method.java
- service/src/main/java/bio/terra/cbas/models/Run.java
- service/src/main/java/bio/terra/cbas/models/RunSet.java
- service/src/main/resources/changelog/changelog.yaml
- service/src/main/resources/changelog/changesets/20221115_add_run_set_columns.yaml
- service/src/test/java/bio/terra/cbas/controllers/TestRunSetsApiController.java
- service/src/test/java/bio/terra/cbas/controllers/TestRunsApiController.java
- service/src/test/java/bio/terra/cbas/runsets/monitoring/TestSmartRunsPoller.java
Closes https://broadworkbench.atlassian.net/browse/WM-1533
> [WM-1533] New GET /run_sets list API

- service/build.gradle
- service/src/main/java/bio/terra/cbas/dao/RunDao.java
- service/src/main/java/bio/terra/cbas/dao/RunSetDao.java
- service/src/main/java/bio/terra/cbas/dao/util/SqlPlaceholderMapping.java
- service/src/main/java/bio/terra/cbas/runsets/monitoring/SmartRunSetsPoller.java
- service/src/test/java/bio/terra/cbas/dao/util/TestSqlPlaceholderMapping.java
- service/src/test/java/bio/terra/cbas/runsets/monitoring/TestSmartRunSetsPoller.java
Adds metrics for WM-1534 and makes sure the last polled timestamps are up to date, even if nothing changes
> WM-1534: Metrics and lastPolled timestamps

- service/src/main/resources/changelog/changelog.yaml
- service/src/main/resources/changelog/changesets/20230104_run_set_prepopulation_target_workflow_2.yaml
Closes https://broadworkbench.atlassian.net/browse/WM-1589
[WM-1589]: https://broadworkbench.atlassian.net/browse/WM-1589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WM-1589] Pre-populate sample run set for target workflow 2

- service/src/main/resources/changelog/changelog.yaml
- service/src/main/resources/changelog/changesets/20230105_run_set_prepopulation_target_workflow_3.yaml
Closes https://broadworkbench.atlassian.net/browse/WM-1593
> [WM-1593] Pre-populate sample run set for target workflow 3

- .github/workflows/publish.yml
https://broadworkbench.atlassian.net/browse/WM-1629
> [WM-1629] Add AppSec Trivy action

- service/src/main/java/bio/terra/cbas/dao/MethodDao.java
> [WM-1657] Workflow order presentation

- service/src/main/java/bio/terra/cbas/dependencies/wes/CromwellService.java
This is currently preventing workflow submission in CBAS as configured for Azure.
> WX-931 Quote log dir string in workflow options

- common/openapi.yml
- service/build.gradle
- service/src/main/java/bio/terra/cbas/common/MetricsUtil.java
- service/src/main/java/bio/terra/cbas/config/CromwellServerConfiguration.java
- service/src/main/java/bio/terra/cbas/controllers/MethodsApiController.java
- service/src/main/java/bio/terra/cbas/controllers/RunSetsApiController.java
- service/src/main/java/bio/terra/cbas/dao/MethodDao.java
- service/src/main/java/bio/terra/cbas/dao/MethodVersionDao.java
- service/src/main/java/bio/terra/cbas/dao/RunSetDao.java
- service/src/main/java/bio/terra/cbas/dependencies/wes/CromwellService.java
- service/src/main/java/bio/terra/cbas/models/Method.java
- service/src/main/java/bio/terra/cbas/models/MethodVersion.java
- service/src/test/java/bio/terra/cbas/controllers/TestMethodsApiController.java
- service/src/test/java/bio/terra/cbas/controllers/TestMethodsApiControllerUnits.java
- service/src/test/java/bio/terra/cbas/controllers/TestRunSetsApiController.java
- service/src/test/java/bio/terra/cbas/dao/TestMethodDao.java
- service/src/test/java/bio/terra/cbas/dao/TestMethodVersionDao.java
Request to endpoint:
```
{
"method_name": "fetch_sra_to_bam method",
"method_description": "fetch_sra_to_bam method description",
"method_source": "GitHub",
"method_version": "master",
"method_url": "https://raw.githubusercontent.com/broadinstitute/viral-pipelines/master/pipes/WDL/workflows/fetch_sra_to_bam.wdl"
}
```
Response from endpoint upon successful creation:
```
{
"method_id": "19def919-5e62-4064-92ac-79392a7d887f",
"run_set_id": "9af55416-d51b-4510-8d75-09ae91c21598"
}
```
Database entries:
```
cbas_db=# select * from method where method_id='19def919-5e62-4064-92ac-79392a7d887f';
-[ RECORD 1 ]---+-------------------------------------
method_id       | 19def919-5e62-4064-92ac-79392a7d887f
name            | fetch_sra_to_bam method
description     | fetch_sra_to_bam method …
```
> [WM-1646] POST /method endpoint

- service/src/main/java/bio/terra/cbas/controllers/RunSetsApiController.java
- service/src/main/java/bio/terra/cbas/dao/RunSetDao.java
- service/src/test/java/bio/terra/cbas/dao/TestRunSetDao.java
Pagination works as expected
Closes https://broadworkbench.atlassian.net/browse/WM-1737
> [WM-1737] Remove hard coded page size limit from GET /run_sets

- service/build.gradle
Brings in changes from https://github.com/broadinstitute/cromwell/pull/7087
> WX-950 Update Cromwell client to latest version

- service/src/main/java/bio/terra/cbas/dao/RunDao.java
- service/src/main/java/bio/terra/cbas/models/Run.java
- service/src/main/java/bio/terra/cbas/runsets/monitoring/SmartRunsPoller.java
- service/src/test/java/bio/terra/cbas/runsets/monitoring/TestSmartRunsPollerFunctional.java
Proof of this working, plus example of showing the error in the UI:
> WM-1799: Make sure errors updating WDS make it to the UI

- common/openapi.yml
- service/src/main/java/bio/terra/cbas/controllers/MethodsApiController.java
- service/src/main/java/bio/terra/cbas/util/methods/WomtoolToCbasInputsAndOutputs.java
- service/src/test/java/bio/terra/cbas/controllers/TestMethodsApiController.java
- service/src/test/java/bio/terra/cbas/controllers/TestMethodsApiControllerUnits.java
- service/src/test/java/bio/terra/cbas/util/methods/TestWomtoolToCbasInputsAndOutputs.java
Closes https://broadworkbench.atlassian.net/browse/WM-1826
> [WM-1826] Allow passing input and output mapping configurations in POST method request

- service/src/main/java/bio/terra/cbas/config/AzureCredentialConfig.java
- service/src/main/java/bio/terra/cbas/config/LeonardoServerConfiguration.java
- service/src/main/java/bio/terra/cbas/config/WdsServerConfiguration.java
- service/src/main/java/bio/terra/cbas/controllers/PublicApiController.java
- service/src/main/java/bio/terra/cbas/dependencies/common/CredentialLoader.java
- service/src/main/java/bio/terra/cbas/dependencies/common/DependencyUrlLoader.java
- service/src/main/java/bio/terra/cbas/dependencies/common/HealthCheck.java
- service/src/main/java/bio/terra/cbas/dependencies/common/HealthCheckable.java
- service/src/main/java/bio/terra/cbas/dependencies/leonardo/AppUtils.java
- service/src/main/java/bio/terra/cbas/dependencies/leonardo/LeonardoClient.java
- service/src/main/java/bio/terra/cbas/dependencies/leonardo/LeonardoService.java
- service/src/main/java/bio/terra/cbas/dependencies/wds/WdsClient.java
- service/src/main/java/bio/terra/cbas/dependencies/wds/WdsService.java
- service/src/main/java/bio/terra/cbas/dependencies/wes/CromwellService.java
- service/src/test/java/bio/terra/cbas/dependencies/common/TestCredentialLoader.java
- service/src/test/java/bio/terra/cbas/dependencies/common/TestDependencyUrlLoader.java
- service/src/test/java/bio/terra/cbas/dependencies/leonardo/TestAppUtils.java
- use `record` for configuration classes
- `Optional` not necessary
- use `setAccessToken()` API to set bearer token
- test code cleanups
- etc
> misc changes

- .github/workflows/publish.yml
Closes https://broadworkbench.atlassian.net/browse/WM-1572
> [WM-1572] Mark `tagOverride` as optional in publish.yaml

- DEVELOPMENT.md
- service/build.gradle
Enables authing to LZ postgres using AKS workload identity.
I installed this version in my app and ensured that the full workflow execution path still works.
> WX-1196 Update Azure identity libs

- .github/workflows/tag-and-publish.yml
Note: depends on https://github.com/broadinstitute/terra-helmfile/pull/4386
> WM-2100: Update terra-helmfile on publish

- service/build.gradle
- service/src/main/java/bio/terra/cbas/dependencies/leonardo/LeonardoService.java
https://precisionmedicineinitiative.atlassian.net/browse/RW-10682
> RW-10682 use new leo client

- common/openapi.yml
- service/src/main/java/bio/terra/cbas/controllers/RunsApiController.java
Place holder API created for run state update.
> WM-2087: Create placeholder api for run status update 

- service/src/main/resources/application.yml
- service/src/test/java/bio/terra/cbas/controllers/VerifyPactsAllControllers.java
Verified locally against https://github.com/DataBiosphere/terra-ui/pull/4183
> [WM-2190] Provider-Side Authz Contract Tests

- service/src/main/resources/changelog/changelog.yaml
- service/src/main/resources/changelog/changesets/20230918_remove_method_prepopulation.yaml
- service/src/test/java/bio/terra/cbas/dao/TestMethodDao.java
- service/src/test/java/bio/terra/cbas/dao/TestRunSetDao.java
Need to confirm timing, but likely will be merged after or around the removal of the feature flag from new Submission UX.
UPDATE: can make the change now - this change does not need to wait until removal of feature flag.
> [WM-2149] Remove pre-staged covid-19 workflows

- service/build.gradle
https://precisionmedicineinitiative.atlassian.net/browse/RW-10774
> RW-10774 update leo client version

- service/build.gradle
- service/src/main/java/bio/terra/cbas/App.java
Tested in BEE and verified output in Azure Portal.
Related PRs:
- https://github.com/broadinstitute/terra-helmfile/pull/4635
- https://github.com/broadinstitute/cromwhelm/pull/279
> [WM-2229] CBAS logs to application insights

- .github/workflows/azure_e2e_test.yml
This PR is just for committing the initial GHA for Azure E2E for testing purposes.
JIRA ticket: https://broadworkbench.atlassian.net/browse/WM-2277
> [WM-2277] Initial GHA for Azure E2E test

- .github/workflows/consumer-contract-tests.yml
- common/local_pacts_config.sh
- service/build.gradle
- service/src/main/java/bio/terra/cbas/dependencies/sam/SamClient.java
- service/src/main/java/bio/terra/cbas/dependencies/sam/SamService.java
- service/src/test/java/bio/terra/cbas/pact/SamPactTest.java
Requests from cbas-consumer to sam-provider:
1. A request for the user's status given user status info request with access token.
2. A request for write permission on workspace given user has write permission.
3. A status request given sam is ok.
Interactions
Given user status info request with access token, upon receiving a request for the user's status from cbas-consumer, with
{
"method": "GET",
"path": "/register/user/v2/self/info",
"headers": {
"Authorization": "Bearer accessToken"
}
}
sam-provider will respond with:
{
"status": 200,
"headers": {
"Content-Type": "application/json; charset=UTF-8"
},
"body": {
"userSubjectId": "testUser",
"userEmail": "test@test.com",
"enabled": true
}
}
Given user has write permission, upon receiving a request for write permission on workspace from …
> [WM-2191] Contract tests cbas consumer sam provider

- service/src/test/java/bio/terra/cbas/controllers/VerifyPactsAllControllers.java
Added provider state for workflow callback
> [WM-2291] Callback API contract tests between Cromwell and CBAS

- service/src/main/java/bio/terra/cbas/controllers/RunSetsApiController.java
- service/src/main/java/bio/terra/cbas/runsets/inputs/InputGenerator.java
- service/src/main/java/bio/terra/cbas/runsets/outputs/OutputGenerator.java
- service/src/main/java/bio/terra/cbas/runsets/types/CbasArray.java
- service/src/main/java/bio/terra/cbas/runsets/types/CbasBoolean.java
- service/src/main/java/bio/terra/cbas/runsets/types/CbasFile.java
- service/src/main/java/bio/terra/cbas/runsets/types/CbasFloat.java
- service/src/main/java/bio/terra/cbas/runsets/types/CbasInt.java
- service/src/main/java/bio/terra/cbas/runsets/types/CbasMap.java
- service/src/main/java/bio/terra/cbas/runsets/types/CbasString.java
- service/src/main/java/bio/terra/cbas/runsets/types/CbasStruct.java
- service/src/main/java/bio/terra/cbas/runsets/types/CbasValue.java
- service/src/main/java/bio/terra/cbas/runsets/types/CoercionException.java
- service/src/main/java/bio/terra/cbas/runsets/types/TypeCoercionException.java
- service/src/main/java/bio/terra/cbas/runsets/types/ValueCoercionException.java
- service/src/test/java/bio/terra/cbas/runsets/types/TestCoercions.java
- service/src/test/java/bio/terra/cbas/runsets/types/TestFileCounting.java
> [WM-1854] Include parameter name in coercion exceptions

- .github/workflows/build-and-test.yml
- .github/workflows/tag-and-publish.yml
- README.md
Redo tag and publish in cbas repo to coordinate cbas and contract tests version updates.
> [QA-2238] Streamline tag and publish job to ensure version updates work in both cbas and contract tests in a coordinated fashion.

- service/build.gradle
- service/src/main/java/bio/terra/cbas/controllers/RunSetsApiController.java
- service/src/main/java/bio/terra/cbas/dao/RunSetDao.java
- service/src/test/java/bio/terra/cbas/controllers/VerifyPactsAllControllers.java
- service/src/test/java/bio/terra/cbas/dao/TestGithubMethodDetailsDao.java
- service/src/test/java/bio/terra/cbas/dao/TestMethodDao.java
- service/src/test/java/bio/terra/cbas/dao/TestMethodVersionDao.java
- service/src/test/java/bio/terra/cbas/dao/TestRunDao.java
- service/src/test/java/bio/terra/cbas/dao/TestRunSetDao.java
- service/src/test/java/bio/terra/cbas/dao/TestRunsFilters.java
- service/src/test/java/bio/terra/cbas/dao/util/ContainerizedDaoTest.java
- service/src/test/java/bio/terra/cbas/dependencies/sam/TestSamService.java
This ticket doesn't directly address the objective of 2414. It's attached to this ticket because I found it difficult to work on the core problem without these changes. I will post a followup PR (that will also be attached to WM-2414) that will address the ticket objectives directly.
> [WM-2414] dao test containers

- DEVELOPMENT.md
Jira ticket: https://broadworkbench.atlassian.net/browse/WX-1720
The following changes have been made to update and improve the documentation for getting started with CBAS development:
- The Postgres version to install was changed from 13 to 14 (Postgres 13 is not available for Apple Silicon Macs)
- The Homebrew install command for Java 17 (Temurin) was updated from a deprecated version of the command
- The Postgres database name for CBAS was updated
- New instructions were added to create the database using the terminal
- Small clarifications/typographical fixes
> [WX-1720] Update Setup Documentation
