DEVELOPMENT.md

There is no redirect yet and hitting the bare path shows an error.
Apologies for the trailing whitespace spam. IntelliJ absolutely insists on doing it, even when I disable in Preferences > Editor > General > On Save

BW-1177 Add Swagger path, update link

---

service/src/main/java/bio/terra/cbas/config/CromwellServerConfiguration.java
service/src/main/java/bio/terra/cbas/controllers/PublicApiController.java
service/src/main/resources/application.yml

CBAS `/status` response when Cromwell is running:
```
{
"ok": true,
"systems": {
"Cromwell": {
"ok": true,
"messages": [
"{}"
]
}
}
}
```
When it's stopped:
```
{
"ok": true,
"systems": {
"Cromwell": {
"ok": false,
"messages": [
"I/O error on GET request for \"http://localhost:8000/engine/v1/status\": Connection refused; nested exception is java.net.ConnectException: Connection refused"
]
}
}
}
```
As per AC the CBAS global status stays `"ok": true` regardless of what Cromwell is doing.
What explicitly does not work yet (future tickets):
- Running anywhere other than locally, with a local Cromwell
- Using a generated API client instead of a generic HTTP library
- As demonstrated by Terra Data Catalog calling Rawls [here](https://github.com/DataBiosphere/terra-data-catalog/blob/main/service …

BW-1250 Basic status check against Cromwell URL

---

common/openapi.yml
service/src/main/java/bio/terra/cbas/controllers/RunsApiController.java

It's 'wes-like' in that the parameters and URL shape is the same. It's not WES-complete because only a handful of parameters are supported. TBD whether we want to go full-WES, but in the absence of reasons not to, I copy/pasted a few of the most relevant sections from the WES spec.

BW-1278: Add a WES-like `/runs` POST endpoint

---

.github/workflows/publish.yml

Upon publishing a new version to this repo, github will now automatically write the tag associated with that new version into the [broadinstitute/cromwhelm repo](https://github.com/broadinstitute/cromwhelm)'s CBAS Helm Chart.
(Continued from https://github.com/DataBiosphere/cbas/pull/23 , because the presubmits don't work if you try to do a PR from a forked repo)

BW-1253: Auto-update helm chart upon CBAS release

---

service/src/main/resources/static/swagger-ui.html

CBAS Swagger not loads as expected both locally and in app setting:
Closes https://broadworkbench.atlassian.net/browse/BW-1313

BW-1313 Fixes Swagger not loading in Cromwell app

---

common/openapi.yml

Adds a relative path to the APIs from swagger. Namely: relative to itself.
Example of swagger working in a deployed app instance:

BW-1365: Make swagger calls relative to where swagger is being hosted

---

buildSrc/build.gradle
common/openapi.yml
service/src/main/java/bio/terra/cbas/controllers/RunSetsApiController.java

- The OpenAPI definition has a little bit of circularity with `ParameterDefinition` declaring it must be `oneOf` its subtypes and its subtypes declaring that they must have `allOf` the `ParameterDefinition` fields. That's not an openapi requirement but it is required to make our specific codegen play nicely. It took a little juggling but we got there in the end.
- You can add `log.info(request.toString());` to the java handler class to see the objects that the codegen creates for us (that's how I produced the examples below). Because of the `oneOf` juggling mentioned above there's a tiny bit more nested than I'd ideally have hand-crafted... but hopefully not too bad, considering.
- In order to avoid breaking changes while the UI catches up, I haven't _removed_ the old `runs` API in this …

BW-1341: Add POST run_sets API

---

common/openapi.yml
service/src/test/java/bio/terra/cbas/controllers/TestRunSetsApiController.java
service/src/test/java/bio/terra/cbas/runsets/inputs/TestInputGeneratorBuildInputs.java
service/src/test/java/bio/terra/cbas/runsets/monitoring/TestSmartRunsPoller.java
service/src/test/java/bio/terra/cbas/runsets/outputs/TestOutputGenerator.java

None of the internal wiring to support them, just add the ability to define optional types in the API spec (and fix up tests!)

WM-1473: Adds swagger definitions for optional types

---

common/openapi.yml
service/src/main/java/bio/terra/cbas/common/MetricsUtil.java
service/src/main/java/bio/terra/cbas/controllers/RunSetsApiController.java
service/src/main/java/bio/terra/cbas/runsets/inputs/InputGenerator.java
service/src/main/java/bio/terra/cbas/runsets/types/CbasBoolean.java
service/src/main/java/bio/terra/cbas/runsets/types/CbasFile.java
service/src/main/java/bio/terra/cbas/runsets/types/CbasFloat.java
service/src/main/java/bio/terra/cbas/runsets/types/CbasInt.java
service/src/main/java/bio/terra/cbas/runsets/types/CbasOptional.java
service/src/main/java/bio/terra/cbas/runsets/types/CbasOptionalNone.java
service/src/main/java/bio/terra/cbas/runsets/types/CbasOptionalSome.java
service/src/main/java/bio/terra/cbas/runsets/types/CbasString.java
service/src/main/java/bio/terra/cbas/runsets/types/CbasValue.java
service/src/main/java/bio/terra/cbas/runsets/types/CoercionException.java
service/src/main/java/bio/terra/cbas/runsets/types/TypeCoercionException.java
service/src/main/java/bio/terra/cbas/runsets/types/ValueCoercionException.java
service/src/test/java/bio/terra/cbas/controllers/TestRunSetsApiController.java
service/src/test/java/bio/terra/cbas/runsets/inputs/TestInputGeneratorBuildOptionalInputs.java
service/src/test/java/bio/terra/cbas/runsets/inputs/TestInputGeneratorBuildPrimitiveInputs.java
service/src/test/java/bio/terra/cbas/runsets/types/TestCoercions.java

To aid validation, includes type and value coercion from Json/WDS types to Cbas recognized types, and on to Cromwell inputs.
From the ticket.
AC:
- File inputs must be declarable via our input definitions.
- Input files are correctly passed along to Cromwell if used in input definitions
- Basic string validation of the file path to make sure it looks like a file
- (put pieces in place in case we need more validation later)
Tests:
- Unit tests against the inputs generator
Metrics:
- Count of files that fail validation and those that don’t
- Counts of GCS, Azure, local, DRS file paths

BW-1474: Add File types as inputs

---

service/src/main/java/bio/terra/cbas/common/MetricsUtil.java
service/src/main/java/bio/terra/cbas/runsets/inputs/InputGenerator.java
service/src/main/java/bio/terra/cbas/runsets/outputs/OutputGenerator.java
service/src/main/java/bio/terra/cbas/runsets/types/CbasBoolean.java
service/src/main/java/bio/terra/cbas/runsets/types/CbasFile.java
service/src/main/java/bio/terra/cbas/runsets/types/CbasFloat.java
service/src/main/java/bio/terra/cbas/runsets/types/CbasInt.java
service/src/main/java/bio/terra/cbas/runsets/types/CbasOptionalNone.java
service/src/main/java/bio/terra/cbas/runsets/types/CbasOptionalSome.java
service/src/main/java/bio/terra/cbas/runsets/types/CbasString.java
service/src/main/java/bio/terra/cbas/runsets/types/CbasValue.java
service/src/test/java/bio/terra/cbas/runsets/outputs/TestOutputGeneratorPrimitives.java
service/src/test/java/bio/terra/cbas/runsets/types/TestCoercions.java
service/src/test/java/bio/terra/cbas/runsets/types/TestFileCounting.java

AC:
- File outputs must be declarable via our output definitions.
- File outputs must be correctly exported back to WDS if used in workflows.
Tests:
- Unit tests against the outputs generator
Metrics:
- Count files that are written back to the data tables (Sara wants to know: How many users are really using this “write to data table” feature?)

BW-1475: Add File types as outputs

---

common/openapi.yml
service/src/main/java/bio/terra/cbas/runsets/types/CbasArray.java
service/src/main/java/bio/terra/cbas/runsets/types/CbasBoolean.java
service/src/main/java/bio/terra/cbas/runsets/types/CbasFile.java
service/src/main/java/bio/terra/cbas/runsets/types/CbasValue.java
service/src/main/java/bio/terra/cbas/runsets/types/ValueCoercionException.java
service/src/test/java/bio/terra/cbas/runsets/inputs/StockInputDefinitions.java
service/src/test/java/bio/terra/cbas/runsets/inputs/TestInputGeneratorBuildArrayInputs.java
service/src/test/java/bio/terra/cbas/runsets/inputs/TestInputGeneratorBuildFileInputs.java
service/src/test/java/bio/terra/cbas/runsets/outputs/StockOutputDefinitions.java
service/src/test/java/bio/terra/cbas/runsets/outputs/TestOutputGeneratorArrays.java

AC in ticket:
> - It is possible to provide a literal array value, or a WDS lookup array value in the input definition.
> - It should be possible to mark arrays as non-empty, in which case CBAS would validate that the array is not empty before sending it.
> 
> Test:
> 
> - Unit tests validating that input definition JSON can be correctly interpreted for array inputs.
> - Unit tests of coercion from WDS values into arrays
> - Unit tests of writing CbasArrays into cromwell inputs
> - Unit tests validating non-emptiness checks.

WM-1511, WM-1512: Array types in inputs

---

DEVELOPMENT.md
common/openapi.yml
service/src/main/java/bio/terra/cbas/controllers/RunsApiController.java

This enables us to query Cromwell about the status of a workflow in CBAS UI.
Also threw in a couple edits to the development setup guide, based on my recent experience.

WX-831 Expose engine id in RunLog

---

service/src/main/java/bio/terra/cbas/common/DateUtils.java
service/src/main/java/bio/terra/cbas/controllers/RunSetsApiController.java
service/src/main/java/bio/terra/cbas/dao/RunDao.java
service/src/main/java/bio/terra/cbas/dao/RunSetDao.java
service/src/main/resources/changelog/changelog.yaml
service/src/main/resources/changelog/changesets/20221122_store_timezone_in_timestamps.yaml

The timestamps in database are stored with timezone information. The timestamps are passed to database in UTC time, and postgres for `timestamp with time zone` data type stores the timestamps internally in UTC format but when displayed converts the timestamp to local time ([reference](https://www.postgresql.org/docs/current/datatype-datetime.html#AEN5811)) and hence in database terminal it is displayed with offset. API responses have timestamps in UTC time and as a result the UI is able to correctly display timestamp based on the browser's timezone.
Previously
Submission created: ~ 5:09 PM EST
Value stored in DB: 2022-09-21 17:09:18.911989
Value returned in API response: 2022-09-21T17:09:18.911+00:00
Value shown in UI: 1:09 pm
Now,
Submission created: ~ 2:54PM EST
Value passed to DB: …

[WM-1461] Store timezone information in timestamps in db and generate time in UTC

---

common/openapi.yml
service/src/main/java/bio/terra/cbas/controllers/RunSetsApiController.java
service/src/main/java/bio/terra/cbas/controllers/RunsApiController.java
service/src/main/java/bio/terra/cbas/dao/RunDao.java
service/src/main/java/bio/terra/cbas/dao/RunSetDao.java
service/src/main/java/bio/terra/cbas/dao/util/WhereClause.java
service/src/main/java/bio/terra/cbas/models/CbasRunSetStatus.java
service/src/main/java/bio/terra/cbas/models/CbasRunStatus.java
service/src/main/java/bio/terra/cbas/runsets/monitoring/SmartRunSetsPoller.java
service/src/main/java/bio/terra/cbas/util/Pair.java
service/src/test/java/bio/terra/cbas/controllers/TestRunSetsApiController.java
service/src/test/java/bio/terra/cbas/controllers/TestRunsApiController.java
service/src/test/java/bio/terra/cbas/dao/TestRunDao.java
service/src/test/java/bio/terra/cbas/models/TestCbasRunSetStatus.java
service/src/test/java/bio/terra/cbas/runsets/monitoring/TestSmartRunSetsPoller.java

"Naive" in the sense that it blocks API responses on results of updating runs in all non-terminal run sets.
We know that won't scale well, but the hope is that it scales "well enough" for public preview.

WM-1534: Implement naive RunSet smart polling

---

service/src/main/java/bio/terra/cbas/config/CromwellServerConfiguration.java
service/src/main/java/bio/terra/cbas/dependencies/wes/CromwellClient.java
service/src/main/java/bio/terra/cbas/dependencies/wes/CromwellService.java

To enable workflow logs to be written to a storage container, the workflow must have a options.json that includes the option "final_workflow_log_dir". This change adds a CBAS config specifying a log directory to write to, and passes this option through the WES API. This is intended to mirror how rawls supplies this option in GCP. 
An outstanding change is required to make WES use this value for workflowOptions on submission.
There is an accompanying helm change to supply this configuration [here](https://github.com/broadinstitute/cromwhelm/pull/153)

WX-864 Enable workflow logs written to storage

---

common/openapi.yml
service/src/main/java/bio/terra/cbas/runsets/types/CbasArray.java
service/src/main/java/bio/terra/cbas/runsets/types/CbasMap.java
service/src/main/java/bio/terra/cbas/runsets/types/CbasValue.java
service/src/test/java/bio/terra/cbas/runsets/inputs/StockInputDefinitions.java
service/src/test/java/bio/terra/cbas/runsets/inputs/TestInputGeneratorBuildMapInputs.java
service/src/test/java/bio/terra/cbas/runsets/outputs/StockOutputDefinitions.java
service/src/test/java/bio/terra/cbas/runsets/outputs/TestOutputGeneratorMaps.java
service/src/test/java/bio/terra/cbas/runsets/types/TestDefinitionParsing.java

Allows for maps in CBAS input/output definitions like:
```json
{
"type": "map",
"key_type": "String",
"value_type": {
"type": "primitive",
"primitive_type": "String"   }
}
```

WM-1669, WM-1633, WM-1637: CBAS Map Types

---

service/src/main/java/bio/terra/cbas/controllers/RunSetsApiController.java
service/src/main/java/bio/terra/cbas/dao/RunSetDao.java
service/src/test/java/bio/terra/cbas/controllers/TestRunSetsApiController.java
service/src/test/java/bio/terra/cbas/dao/TestRunSetDao.java

Tested locally:
GET /run_sets doesn't return templated run sets and  UI only displays 1 submission that I had run as expected
Closes https://broadworkbench.atlassian.net/browse/WM-1713

[WM-1713] Don't return templated run sets in GET /run_sets API

---

service/src/main/resources/changelog/changelog.yaml
service/src/main/resources/changelog/changesets/20230217_ensure_covid_19_methods_order.yaml
service/src/test/java/bio/terra/cbas/dao/TestMethodDao.java

The methods appear in the order as expected:
Closes https://broadworkbench.atlassian.net/browse/WM-1722

[WM-1722] Ensure order for Covid-19 methods

---

common/openapi.yml
service/src/main/java/bio/terra/cbas/common/exceptions/InputProcessingException.java
service/src/main/java/bio/terra/cbas/runsets/inputs/InputGenerator.java
service/src/main/java/bio/terra/cbas/runsets/types/CbasStruct.java
service/src/main/java/bio/terra/cbas/runsets/types/CbasValue.java
service/src/test/java/bio/terra/cbas/runsets/inputs/StockInputDefinitions.java
service/src/test/java/bio/terra/cbas/runsets/inputs/TestInputGeneratorBuildStructInputs.java
service/src/test/java/bio/terra/cbas/runsets/types/TestDefinitionParsing.java

As an implementation note, it turned out that the "Direct Field Access from WDS" option to specify where structs come from (see [conversation](https://docs.google.com/document/d/1WFQjd1RUuK3hgTkZ_JF1W8X1Q54k4kvW4YrI-yaScnI/edit#bookmark=id.mkcfx24ge0o6)) was so easy to implement, we basically got it for free. I've added a test case for it.

WM-1635, WM-1642: Struct type support in CBAS backend

---

service/src/main/java/bio/terra/cbas/config/SamServerConfiguration.java
service/src/main/java/bio/terra/cbas/dependencies/common/ScheduledHealthChecker.java
service/src/main/java/bio/terra/cbas/dependencies/sam/SamClient.java
service/src/main/java/bio/terra/cbas/dependencies/sam/SamService.java
service/src/main/resources/application.yml

Related Cromwhelm PR: https://github.com/broadinstitute/cromwhelm/pull/266
Testing:
I was able to test CBAS and chart changes by deploying them to a running Workflows app in dev. Logs from CBAS pod after upgrade shows Sam url being passed and successful health check:
```
...
{"timestampSeconds":1690567109,"timestampNanos":344000000,"severity":"INFO","message":"Started App in 61.901 seconds (JVM running for 67.713)","serviceContext":{"service":"cbas","version":"unknown"},"context":"default","thread":"main","logger":"bio.terra.cbas.App","logging.googleapis.com/sourceLocation":{"file":"org/springframework/boot/StartupInfoLogger.java","line":61,"function":"org.springframework.boot.StartupInfoLogger.logStarted"}}
{"timestampSeconds":1690567112,"timestampNanos":239000000,"severity":"INFO","messa …
```

[WM-2122] Add Sam client

---

common/openapi.yml
service/src/main/java/bio/terra/cbas/controllers/GlobalExceptionHandler.java
service/src/main/java/bio/terra/cbas/controllers/MethodsApiController.java
service/src/main/java/bio/terra/cbas/controllers/RunSetsApiController.java
service/src/main/java/bio/terra/cbas/dao/RunSetDao.java
service/src/main/java/bio/terra/cbas/dao/mappers/RunSetMapper.java
service/src/main/java/bio/terra/cbas/models/RunSet.java
service/src/main/resources/changelog/changelog.yaml
service/src/main/resources/changelog/changesets/20230808_add_user_id_column.yaml
service/src/test/java/bio/terra/cbas/controllers/TestMethodsApiController.java
service/src/test/java/bio/terra/cbas/controllers/TestRunSetsApiController.java
service/src/test/java/bio/terra/cbas/controllers/TestRunsApiController.java
service/src/test/java/bio/terra/cbas/controllers/VerifyPactsAllControllers.java
service/src/test/java/bio/terra/cbas/dao/TestRunSetDao.java
service/src/test/java/bio/terra/cbas/runsets/monitoring/TestRunSetAbortManager.java
service/src/test/java/bio/terra/cbas/runsets/monitoring/TestSmartRunSetsPoller.java
service/src/test/java/bio/terra/cbas/runsets/monitoring/TestSmartRunsPollerFunctional.java

This PR adds a `user_id` column to the `run_set` table, which is populated based on the token provided in the request. There are many files that were updated just to include the extra parameter in the RunSet constructor, so I have commented where the important changes were made.
Note that this PR does not expose `user_id` on API responses - it's simply responsible for storing this new field in the database.

[WM-2093] Add user id to RunSet

---

service/src/main/java/bio/terra/cbas/config/BeanConfig.java
service/src/main/resources/application.yml

Disables the `FAIL_ON_UNKNOWN_PROPERTIES` flag on our custom `ObjectMapper` bean. Funnily enough, this is typically disabled by default by Spring, but since we are overriding the ObjectMapper Bean we need to explicitly disable it. Tested locally by firing some `POST /run_sets` requests with `"foo": "bar"` in the request body

[WM-2178] CBAS ignores unknown properties in request body

---

service/src/main/java/bio/terra/cbas/dependencies/sam/SamService.java
service/src/main/resources/application.yml
service/src/main/resources/logback.xml
service/src/test/java/bio/terra/cbas/controllers/TestRunSetsApiController.java
service/src/test/java/bio/terra/cbas/dependencies/sam/TestSamService.java

This PR adds user awareness to the existing logging system. Check the code comment in `SamService.java` for further explanation - it is very similar to how we already include requestId in our logs (though the heavy lifting is done by terra-common-lib there).

[WM-2095] User ID in Logs

---

.github/workflows/tag-and-publish.yml

CBAS `tag-and-publish` workflow was failing on many PRs with messages like `fatal: '[WM-2095]-cbas-update-0.0.148' is not a valid branch name`. Example [here](https://github.com/DataBiosphere/cbas/actions/runs/5891609214/job/15979029163). Git doesn't like brackets in branch names, so removing the brackets should fix this issue (we can see a successful PR was created [here](https://github.com/broadinstitute/terra-helmfile/pull/4442) when brackets were omitted in the original PR itself)
For anyone curious - this wasn't an issue in cromwhelm because we were making direct commits rather than checking out a branch/PR.
[WM-2095]: https://broadworkbench.atlassian.net/browse/WM-2095?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WM-2184] Remove brackets from Jira ID

---

DEVELOPMENT.md
service/src/main/java/bio/terra/cbas/controllers/RunSetsApiController.java
service/src/main/java/bio/terra/cbas/runsets/monitoring/SmartRunsPoller.java
service/src/test/java/bio/terra/cbas/controllers/TestRunSetsApiController.java

Small change proposed to address the rocky UI experience immediately following a workflow submission.
New experience:
https://github.com/DataBiosphere/cbas/assets/67511512/b1d9357c-e634-4fcc-9fcc-f102b6d07e2e

[WM-2208] Initialize runs with INITIALIZING state

---

service/src/main/java/bio/terra/cbas/config/CbasApiConfiguration.java
service/src/main/java/bio/terra/cbas/controllers/RunSetsApiController.java
service/src/main/java/bio/terra/cbas/dependencies/wes/CromwellService.java
service/src/main/resources/application.yml
service/src/test/java/bio/terra/cbas/controllers/TestRunSetsApiController.java
service/src/test/java/bio/terra/cbas/controllers/VerifyPactsAllControllers.java

For timing comparison, ran `fetch_sra_to_bam` with 100 workflows with the current version of CBAS and with a version built from this branch:
- current/individual submissions: ~45 seconds for network response
- new/batched submissions: ~16 seconds for network response

[WM-1792] Submit workflows as batch to Cromwell

---

service/src/main/java/bio/terra/cbas/dependencies/sam/SamClient.java

Utilizing the same fix for the above as https://github.com/broadinstitute/rawls/pull/2154, which was reported [here](https://broadworkbench.atlassian.net/browse/WOR-641?focusedCommentId=72249) to resolve the issue. Does not seem to be related to access token issues, as logs and subsequent calls with the same token were successful.

[WM-2253] Use HTTP 1.1 for sam client

---

service/src/main/java/bio/terra/cbas/config/CbasNetworkConfiguration.java
service/src/main/java/bio/terra/cbas/controllers/RunsApiController.java
service/src/main/java/bio/terra/cbas/dependencies/wes/CromwellService.java
service/src/test/java/bio/terra/cbas/controllers/TestRunSetsApiController.java

Adds an additional workflow option to activate workflow completion callbacks (see https://github.com/broadinstitute/cromwell/pull/7213/files under `docs/cromwell_features/WorkflowCallback.md`).
Note: doesn't start doing until without also having:

WM-2123: Request callback in submissions to Cromwell

---

service/src/main/java/bio/terra/cbas/controllers/RunsApiController.java
service/src/main/java/bio/terra/cbas/dao/RunDao.java
service/src/main/java/bio/terra/cbas/dao/RunSetDao.java
service/src/test/java/bio/terra/cbas/controllers/TestRunSetsApiController.java
service/src/test/java/bio/terra/cbas/controllers/TestRunsApiController.java
service/src/test/java/bio/terra/cbas/dao/TestRunDao.java
service/src/test/java/bio/terra/cbas/dao/TestRunSetDao.java
service/src/test/java/bio/terra/cbas/dao/TestRunsFilters.java
service/src/test/java/bio/terra/cbas/runsets/results/TestRunCompletionHandlerUnit.java

1. Added implementation of getting Run record by the runId (WorkflowId) and updated controller code to use it.
2. TestRunDao renamed to TestRunsFilters according to the test logic.
3. TestRunDao validates a new method with a call to db. Both TestRunDao and TestRunSetDao are manual tests requiring an explicit db cleanup after. Something to re-think later for a validation strategy.

[WM-2254] Workflow completion callback hitting run not found exception

---

service/src/main/resources/changelog/changelog.yaml
service/src/main/resources/changelog/changesets/20231102_set_table_role.yaml

Tested in a live app with the resulting database ownership being correctly updated:
```
cbas_zy641f=> \dt
List of relations
Schema |         Name          | Type  |    Owner
--------+-----------------------+-------+-------------
public | databasechangelog     | table | cbas_zy641f
public | databasechangeloglock | table | cbas_zy641f
public | method                | table | cbas_zy641f
public | method_version        | table | cbas_zy641f
public | run                   | table | cbas_zy641f
public | run_set               | table | cbas_zy641f
(6 rows)
```

WM-2356: Set table role correctly

---

service/src/main/java/bio/terra/cbas/runsets/monitoring/SmartRunsPoller.java
service/src/test/java/bio/terra/cbas/runsets/monitoring/TestSmartRunsPollerFunctional.java

See thread [here](https://broadinstitute.slack.com/archives/GHYJZ2ZE0/p1701379476185339) for more info. Currently the only fix in place is to surface the internal error in addition to the generic message. If users are still seeing this in the new multi-user app layout, the Cromwell client/spec may need to be updated with the proper WorkflowMetadataResponse object structure

[WM-1865] Surface Cromwell-level error in response

---

.github/workflows/tag-and-publish.yml
client/artifactory.gradle

Took a first pass at wiring up publishing the cbas client to artfactory.  Tried to follow what data-catalog was doing as per the comment in the artifactory.gradle file.
If someone could please verify that the secrets being used in the github action are available in this repo:
* ARTIFACTORY_USERNAME
* ARTIFACTORY_PASSWORD

WM-2424: Publish cbas client to artifactory

---

service/build.gradle

Adopts JAR from https://github.com/broadinstitute/cromwell/pull/7352
`https://lz7388ada396994bb48ea5c87a02eed673689c82c2af423d03.servicebus.windows.net/terra-app-6e61e365-081b-4511-820a-c6c29dc882da-cd9ecb9e-936f-4027-b05b-05be7ab3a972/cbas/status`
Before:
```
{
"ok": true,
"systems": {
"sam": {
"ok": true,
"messages": [
"class SystemStatus {\n    ok: true\n    systems: {GoogleGroups=class SubsystemStatus {\n        ok: true\n        messages: null\n    }, GooglePubSub=class SubsystemStatus {\n        ok: true\n        messages: null\n    }, GoogleIam=class SubsystemStatus {\n        ok: true\n        messages: null\n    }, Database=class SubsystemStatus {\n        ok: true\n        messages: null\n    }}\n}"
]
},
"leonardo": {
"ok": true,
"messages": [
"class SystemStatus {\n    ok: …
```

WX-1396 Cromwell client allow additional properties

---

client/swagger.gradle

It seems there is a[ breaking change introduced](https://stackoverflow.com/a/46405129) in jersey version 2.26  that caused this library to not be needed in new versions but still needed in previous versions.  When I tried using this client w/o this this change i ran into this issue
```
java.lang.IllegalStateException: InjectionManagerFactory not found.
at org.glassfish.jersey.internal.inject.Injections.lambda$lookupInjectionManagerFactory$0(Injections.java:74)
at java.base/java.util.Optional.orElseThrow(Optional.java:403)
at org.glassfish.jersey.internal.inject.Injections.lookupInjectionManagerFactory(Injections.java:74)
at org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:44)
at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.ja …
```

TSPS-147 add jersey-hk2 dependency to cbas client generation

---

.gitignore
service/build.gradle
service/src/main/java/bio/terra/cbas/App.java
service/src/main/java/bio/terra/cbas/common/MicrometerMetrics.java
service/src/main/java/bio/terra/cbas/controllers/RunsApiController.java
service/src/main/java/bio/terra/cbas/runsets/monitoring/SmartRunsPoller.java
service/src/main/java/bio/terra/cbas/runsets/results/RunCompletionHandler.java
service/src/main/resources/application.yml
service/src/main/resources/applicationinsights.json
service/src/test/java/bio/terra/cbas/controllers/TestRunsApiController.java
service/src/test/java/bio/terra/cbas/controllers/VerifyPactsAllControllers.java
service/src/test/java/bio/terra/cbas/dao/TestMethodDao.java
service/src/test/java/bio/terra/cbas/runsets/monitoring/TestSmartRunsPollerFunctional.java
service/src/test/java/bio/terra/cbas/runsets/results/TestRunCompletionHandlerFunctional.java
service/src/test/java/bio/terra/cbas/runsets/results/TestRunCompletionHandlerUnit.java

Note: depends on extra env variables being added in https://github.com/broadinstitute/terra-helmfile/pull/4980 for the custom dimensions.
Sample actuator API metrics (MRG logs):
Sample custom application metrics (application insights logs:
(note: counting a total of 6 workflow completions, all via the callback API)

WM-2302: Enable actuator API and micrometer custom metrics

---

service/src/main/java/bio/terra/cbas/controllers/RunsApiController.java
service/src/main/java/bio/terra/cbas/runsets/results/RunCompletionHandler.java
service/src/test/java/bio/terra/cbas/runsets/results/TestRunCompletionHandlerFunctional.java

Tested by:
- Created a "sabotaged" branch which threw API exceptions 60% of the time
- Submitted a set of workflows
- Watched logs for evidence of the error being thrown in CBAS
- Watched logs for evidence of Cromwell retrying the callback
- Observed that all workflows eventually succeeded and data tables were updated
- Observed that the completion trigger was indeed still callback
(Note: there was actually both a smartpoller and callback entry, indicating that the callback happened _as well as_ a successful update on smartpolling. That's a good thing - it means the fallback mechanism of letting the smartpoller pick up if the callback gives up is _also_ working well)

WM-2487: Treat failure to update WDS as retryable

---

.github/workflows/build-and-test.yml
.github/workflows/tag-and-publish.yml

Combine `tag-job` and `publish-job` into one job (`tag-and-publish-job`). This is because the `settings.gradle` need to be updated to the new release tag prior to publishing `cbas-client` to artifactory with the new version.

[QA-2240] Combine tag and publish into one job

---

.github/workflows/build-and-test.yml

The `tag-and-publish` job should run on `merge` even the integration test may be flaky at times. As long as integration tests pass during PRs we should be good.

[QA-2244] Do not block tag-and-publish on merge

---

.github/workflows/tag-and-publish.yml

This PR removes the steps that update the CBAS image in cromwhlem repo. As a result of this, fewer CROMWELL version update PRs will be created from cromwhlem to Leo.
Closes https://broadworkbench.atlassian.net/browse/WM-2409

[WM-2409] Stop updating CBAS image in cromwhelm charts

---

service/src/main/java/bio/terra/cbas/controllers/MethodsApiController.java
service/src/main/java/bio/terra/cbas/dao/MethodVersionDao.java
service/src/main/java/bio/terra/cbas/dao/RunDao.java
service/src/main/java/bio/terra/cbas/dao/RunSetDao.java
service/src/main/java/bio/terra/cbas/dao/mappers/GithubMethodVersionDetailsMapper.java
service/src/main/java/bio/terra/cbas/dao/mappers/MethodVersionMappers.java
service/src/main/java/bio/terra/cbas/models/GithubMethodVersionDetails.java
service/src/main/java/bio/terra/cbas/models/MethodVersion.java
service/src/main/java/bio/terra/cbas/models/RunSet.java
service/src/main/resources/changelog/changelog.yaml
service/src/main/resources/changelog/changesets/20240416_github_method_version_details.yaml
service/src/test/java/bio/terra/cbas/controllers/TestMethodsApiController.java
service/src/test/java/bio/terra/cbas/controllers/TestRunSetsApiController.java
service/src/test/java/bio/terra/cbas/controllers/TestRunsApiController.java
service/src/test/java/bio/terra/cbas/dao/TestMethodDao.java
service/src/test/java/bio/terra/cbas/dao/TestMethodVersionDao.java
service/src/test/java/bio/terra/cbas/dao/TestRunDao.java
service/src/test/java/bio/terra/cbas/dao/TestRunSetDao.java
service/src/test/java/bio/terra/cbas/dao/util/ContainerizedDatabaseTest.java
service/src/test/java/bio/terra/cbas/initialization/TestCloneRecoveryService.java
service/src/test/java/bio/terra/cbas/initialization/TestCloneRecoveryTransactionService.java
service/src/test/java/bio/terra/cbas/pact/VerifyPactsAllControllers.java
service/src/test/java/bio/terra/cbas/runsets/monitoring/TestSmartRunsPollerFunctional.java
service/src/test/java/bio/terra/cbas/runsets/results/TestRunCompletionHandlerFunctional.java
service/src/test/java/bio/terra/cbas/runsets/results/TestRunCompletionHandlerUnit.java

Adds:
- `GithubMethodVersionDetails` table to store github-specific fields
- Inside that, a required githash field.
Updates:
- DAO methods to store (or not store) the field
- DAO methods to retrieve (or not retrieve) the field
- Test methods to make sure the retrieval is working properly
Note: as part of this ticket I ended up removing a couple of unexpected (and redundant?) GROUP BY constructs from various queries. The tests we have are all still passing. Question for reviewers: do these updates seem correct?

WM-2575: Add DB column for githash

---

service/src/test/java/bio/terra/cbas/dao/TestRoleSetup.java
service/src/test/java/bio/terra/cbas/dao/util/ContainerizedDatabaseTest.java

Example test failure message for missing the role reassignment: `Table github_method_version_details is owned by 'test_user' but should be owned by 'test_role'. Do you need to update the 20231102_set_table_role.yaml changeset?`

WM-2640: Validate table ownership role is correctly updated

---

service/build.gradle

Example API output below.
Note 1: The `version` field is the one we care about
Note 2: Yeah it would be cool to have git too, but not in this PR!
Before:
```json
{
"git": {
}
}
```
After:
```json
{
"git": {
},
"build": {
"artifact": "service",
"name": "service",
"time": "2024-06-03T18:31:45.429Z",
"version": "0.0.221",
"group": "bio.terra"
}
}
```

WM-2661: Add buildInfo to info endpoint

---

service/src/main/java/bio/terra/cbas/dao/RunDao.java
service/src/main/java/bio/terra/cbas/models/Run.java
service/src/main/java/bio/terra/cbas/runsets/monitoring/RunSetAbortManager.java
service/src/test/java/bio/terra/cbas/dao/TestRunDao.java
service/src/test/java/bio/terra/cbas/dao/TestRunsFilters.java

Eventually we might want to raise or parameterize this length. In the mean time, make it safe

WM-2584: Make run creation and updating error-length-safe

---

service/src/main/java/bio/terra/cbas/common/MicrometerMetrics.java
service/src/main/java/bio/terra/cbas/controllers/RunsApiController.java
service/src/main/java/bio/terra/cbas/runsets/monitoring/SmartRunsPoller.java

Jira ticket: https://broadworkbench.atlassian.net/browse/WM-2643
The PR splits the `run_completion` metric, which was recording both the smart poller and callback metrics, into 2 metrics. 
Tested changes by manually updating CBAS image in dev app

[WM-2643] Cromwell callback and smart poller metrics

---

service/src/main/java/bio/terra/cbas/models/CbasRunStatus.java
service/src/test/java/bio/terra/cbas/models/TestCbasRunStatus.java
service/src/test/java/bio/terra/cbas/runsets/monitoring/TestSmartRunsPollerFunctional.java

Jira ticket: https://broadworkbench.atlassian.net/browse/WM-2670
Current status transitions that was causing the workflow to revert back to Queued state mid-run:
- When a workflow is being processed in CBAS upon submission, it is marked in `Queued` state
- When CBAS submits that workflow to Cromwell, it is marked in `Initializing` state
- Now when Cromwell receives a workflow it stores the workflow in DB in `Submitted` state 
- When CBAS polls for status update it would mark the same run back to `Queued` state because of the mapping in `fromCromwellStatus()` and as a result the status transitions were Queued -> Initializing -> Queued -> Running -> other states
Proposed changes:
When Cromwell returns a workflow in `Submitted` state, the corresponding CBAS status is now `Initializing` and …

[WM-2670] Runs submitted to Cromwell are marked in Initializing status in CBAS

---

service/src/main/java/bio/terra/cbas/models/RunAndRecordDetails.java
service/src/main/java/bio/terra/cbas/models/RunSetSubmissionParameters.java
service/src/main/java/bio/terra/cbas/models/SubmitRunSetResponse.java
service/src/main/java/bio/terra/cbas/service/RunSetsService.java

These refactors address sonarcloud's "cognitive complexity" warnings in [WM-2642_submission-scaling-metrics](https://github.com/DataBiosphere/cbas/tree/WM-2642_submission-scaling-metrics) by splitting `buildInputsAndSubmitRunSet` into two methods, `buildInputs` and `submitRunSet`

[WM-2642] refactor submission methods

---

client/build.gradle
service/build.gradle
service/src/main/java/bio/terra/cbas/controllers/PublicApiController.java

Jira ticket: https://broadworkbench.atlassian.net/browse/WM-2703
It seems all of a sudden pact tests started failing because build client wasn't able to find `build-info-extractor` POM file. This PR fixes that. I have upgraded CBAS to latest version of [com.jfrog.artifactory](https://github.com/jfrog/artifactory-gradle-plugin). This version is also [the one used by WDS](https://github.com/DataBiosphere/terra-workspace-data-service/blob/135b8301f34102e0dcde19c5a57857d07b663a6e/client/build.gradle#L6).
Failure:
```
A problem occurred configuring project ':client'.
> Could not resolve all files for configuration ':client:classpath'.
> Could not find org.jfrog.buildinfo:build-info-extractor:2.21.0.
Searched in the following locations:
- …
```

[WM-2703] Upgrade 'com.jfrog.artifactory' version

---

client/build.gradle
common/openapi.yml
service/src/main/java/bio/terra/cbas/controllers/PublicApiController.java
service/src/main/resources/capabilities.json
service/src/test/java/bio/terra/cbas/controllers/TestPublicApiController.java

Jira ticket: https://broadworkbench.atlassian.net/browse/WM-2683
This PR adds new `capabilities` API. The response is a JSON object that is defined in `capabilities.json` file. The response structure is [similar to WDS' capabilities API](https://github.com/DataBiosphere/terra-workspace-data-service/wiki/Capabilities-API#response-structure) where response is:
- flat list of key-value pairs where keys are strings and values should be primitive type
- keys use dot notation to group related keys into a namespace, e.g. `submission.limits`
Wiki documentation: https://github.com/DataBiosphere/cbas/wiki/Capabilities-API
Response:
```
{
"submission.limits.maxOutputs": 300,
"submission.limits.maxWorkflows": 100,
"submission.limits.maxInputs": 200
}
```
TODO:

[WM-2683] Adds /capabilities API

---

buildSrc/build.gradle
service/publishing.gradle
service/src/main/resources/logback.xml

Jira: https://broadworkbench.atlassian.net/browse/AN-1, https://broadworkbench.atlassian.net/browse/AN-212
**jre:17-12-distroless** - I am following Data Catalog team's principle of trying to make the least changes in base image possible so that it doesn't break anything in CBAS (instead of upgrading to JRE 21). [This PR](https://github.com/DataBiosphere/terra-data-catalog/pull/177#issue-2573613554) has a good description on what and why. [This Slack thread](https://broadinstitute.slack.com/archives/C0DSD41QT/p1728328182615109) also has details on why jre:17 debain 12 image was created.
**spring-web** dependency fix -
Before upgrade
```
service % ../gradlew dependencyInsight --dependency org.springframework:spring-web
> Task :service:dependencyInsight
org.springframework:spring-web:6.1.4 …
```

[AN-1][AN-212] Upgrade base image to jre:17-12-distroless and spring-boot-gradle-plugin to 3.3.5

---

.github/workflows/build-and-test.yml

The cache backend service has been rewritten from the ground up for improved performance and reliability. [actions/cache](https://github.com/actions/cache) now integrates with the new cache service (v2) APIs.
The new service will gradually roll out as of February 1st, 2025. The legacy service will also be sunset on the same date. Changes in these release are fully backward compatible.
More info here: https://github.com/marketplace/actions/cache

CORE-246 Upgrading to cache v4
